# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\pycharm_workspace\HuoyingHelper\PointWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(296, 216)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.point_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.point_edit.setGeometry(QtCore.QRect(20, 30, 113, 20))
        self.point_edit.setObjectName("point_edit")
        self.resize_btn = QtWidgets.QPushButton(self.centralwidget)
        self.resize_btn.setGeometry(QtCore.QRect(140, 30, 56, 17))
        self.resize_btn.setObjectName("resize_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 296, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.resize_btn.setText(_translate("MainWindow", "设置"))
